# Generated by Django 5.2.4 on 2026-07-19 20:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # La dipendenza da ("auth", "0012_...") e i campi groups / user_permissions
    # sono stati tolti da questa migrazione quando django.contrib.auth e' stato
    # disinstallato insieme al pannello /admin/. Senza la modifica un database
    # creato da zero non partirebbe: "auth" non e' piu' nel grafo. Lo schema
    # finale non cambia — quei due campi venivano comunque rimossi dalla 0007.
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "code",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Difficolta",
            fields=[
                (
                    "code",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Importanza",
            fields=[
                (
                    "code",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Livello",
            fields=[
                (
                    "code",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StatoLezione",
            fields=[
                (
                    "code",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tipologia",
            fields=[
                (
                    "code",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", learning.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Lezione",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descrizione", models.TextField(blank=True)),
                ("ordine_percorso", models.PositiveIntegerField(unique=True)),
                ("obiettivo_didattico", models.TextField()),
                ("competenze", models.JSONField(default=list)),
                ("durata_min", models.PositiveSmallIntegerField()),
                ("errori_tipici", models.JSONField(default=list)),
                (
                    "ordine_mvp",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("fase_roadmap", models.CharField(max_length=80)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="learning.area"
                    ),
                ),
                (
                    "difficolta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="learning.difficolta",
                    ),
                ),
                (
                    "importanza_mvp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="learning.importanza",
                    ),
                ),
                (
                    "livello",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="learning.livello",
                    ),
                ),
            ],
            options={
                "ordering": ["ordine_mvp", "ordine_percorso"],
            },
        ),
        migrations.CreateModel(
            name="Prerequisito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lezione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vincoli",
                        to="learning.lezione",
                    ),
                ),
                (
                    "richiede_lezione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="richiesta_da",
                        to="learning.lezione",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lezione",
            name="prerequisiti",
            field=models.ManyToManyField(
                related_name="sblocca",
                through="learning.Prerequisito",
                to="learning.lezione",
            ),
        ),
        migrations.CreateModel(
            name="Progresso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("bloccata", "Bloccata"),
                            ("disponibile", "Disponibile"),
                            ("in_corso", "In corso"),
                            ("completata", "Completata"),
                        ],
                        default="disponibile",
                        max_length=12,
                    ),
                ),
                (
                    "punteggio",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("completata_il", models.DateTimeField(blank=True, null=True)),
                ("minuti_effettivi", models.PositiveIntegerField(default=0)),
                (
                    "lezione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressi",
                        to="learning.lezione",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modalita",
                    models.CharField(
                        choices=[
                            ("guidato", "Esercizio guidato"),
                            ("finale", "Quiz finale"),
                        ],
                        max_length=10,
                    ),
                ),
                ("titolo", models.CharField(max_length=160)),
                (
                    "lezione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="learning.lezione",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quesito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordine", models.PositiveSmallIntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("scelta_multipla", "Scelta multipla"),
                            ("completamento", "Completamento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("testo", models.TextField()),
                ("opzioni", models.JSONField(blank=True, default=list)),
                ("risposta_corretta", models.CharField(max_length=300)),
                ("spiegazione", models.TextField()),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quesiti",
                        to="learning.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["ordine"],
            },
        ),
        migrations.CreateModel(
            name="SezioneLezione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordine", models.PositiveSmallIntegerField()),
                ("tipo_sezione", models.CharField(max_length=80)),
                ("contenuto", models.JSONField(default=dict)),
                ("formato_web", models.CharField(default="testo", max_length=40)),
                (
                    "lezione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sezioni",
                        to="learning.lezione",
                    ),
                ),
            ],
            options={
                "ordering": ["ordine"],
            },
        ),
        migrations.AddField(
            model_name="lezione",
            name="stato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="learning.statolezione"
            ),
        ),
        migrations.AddField(
            model_name="lezione",
            name="tipologia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="learning.tipologia"
            ),
        ),
        migrations.AddConstraint(
            model_name="prerequisito",
            constraint=models.UniqueConstraint(
                fields=("lezione", "richiede_lezione"), name="prerequisito_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="prerequisito",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lezione", models.F("richiede_lezione")), _negated=True
                ),
                name="no_auto_prerequisito",
            ),
        ),
        migrations.AddConstraint(
            model_name="progresso",
            constraint=models.UniqueConstraint(
                fields=("utente", "lezione"), name="progresso_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="quiz",
            constraint=models.UniqueConstraint(
                fields=("lezione", "modalita"), name="quiz_modalita_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="quesito",
            constraint=models.UniqueConstraint(
                fields=("quiz", "ordine"), name="ordine_quesito_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="sezionelezione",
            constraint=models.UniqueConstraint(
                fields=("lezione", "ordine"), name="ordine_sezione_unico"
            ),
        ),
    ]
