# Generated by Django 5.2.4 on 2026-07-20

import django.core.validators
from django.db import migrations, models


def normalize_areas_and_priorities(apps, schema_editor):
    Area = apps.get_model("learning", "Area")
    Lezione = apps.get_model("learning", "Lezione")

    Lezione.objects.filter(area_id="PRN").delete()
    Area.objects.filter(code="PRN").delete()
    for importance, priority in {
        "Essenziale": "P0",
        "Consigliata": "P1",
        "Secondaria": "P2",
    }.items():
        Lezione.objects.filter(importanza_mvp_id=importance).update(priorita=priority)


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lezione",
            name="priorita",
            field=models.CharField(
                choices=[
                    ("P0", "MVP Essenziale"),
                    ("P1", "MVP Consigliata"),
                    ("P2", "MVP Secondaria"),
                    ("P3", "Post-MVP"),
                ],
                default="P3",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="lezione",
            name="ordine_percorso",
            field=models.PositiveIntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(98),
                ],
            ),
        ),
        migrations.RunPython(normalize_areas_and_priorities, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="lezione",
            constraint=models.CheckConstraint(
                condition=models.Q(("area_id__in", ["GRA", "VOC", "COM"])),
                name="lezione_area_supportata",
            ),
        ),
        migrations.AddConstraint(
            model_name="lezione",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordine_percorso__gte", 1), ("ordine_percorso__lte", 98)),
                name="ordine_percorso_1_98",
            ),
        ),
    ]
