# Generated by Django 5.2.4 on 2026-07-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_lezione_priorita_alter_lezione_ordine_percorso_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresso",
            name="assegnata",
            field=models.BooleanField(default=False),
        ),
    ]
