# Generated by Django 5.2.4 on 2026-07-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_progresso_assegnata"),
    ]

    operations = [
        migrations.AddField(
            model_name="lezione",
            name="categoria",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
