# Generated by Django 5.2.4 on 2026-08-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_lezione_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
